trigger:
- main

pool: Test

stages: 
- stage: 
  displayName: TerraformInstallInit
  jobs:
  - job: TerraformInstallInit
    steps:
    - task: TerraformInstaller@1
      displayName: TerraformInit
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      displayName: TerraformInit
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Env/Dev'
        backendAzureRmUseEntraIdForAuthentication: false
        backendServiceArm: 'ServiceConnection'
        backendAzureRmResourceGroupName: 'Terraform-Stg-Account'
        backendAzureRmStorageAccountName: 'tfstgact'
        backendAzureRmContainerName: 'terraform'
        backendAzureRmKey: 'terraform.tfstate'
  
  - job: TerraformPlan
    displayName: TerraformPlan
    steps:
    - task: TerraformTask@5
      displayName: TerraformPlan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Env/dev'
        environmentServiceNameAzureRM: 'ServiceConnection'
    

